name: Test Build Image
on:
  pull_request:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.read-json.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read JSON file
        id: read-json
        run: |
          jq --version
          echo "TERRAFORM_VERSION=$(jq -r '.TERRAFORM_VERSION' versions.json)" >> $GITHUB_ENV
          echo "ATMOS_VERSION=$(jq -r '.ATMOS_VERSION' versions.json)" >> $GITHUB_ENV
          echo "Terraform version: $(jq -r '.TERRAFORM_VERSION' versions.json)"
          echo "Atmos version: $(jq -r '.ATMOS_VERSION' versions.json)"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Use JSON file values
        run: |
          echo "Terraform version: ${{fromJson(needs.job1.outputs.matrix)}}"
          echo "Atmos version: ${{ needs.job1.outputs.matrix.ATMOS_VERSION }}"
      #echo "Atmos version: $(jq -r '.ATMOS_VERSION' versions.json)"
